
replicaCount: 1

image:
  repository: linuxserver/sonarr
  tag: latest
  pullPolicy: IfNotPresent

env:
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"
  - name: "TZ"
    value: "US/New_York"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - sonarr.bangedyour.mom
  tls:
   - secretName: sonarr-bangedyour-mom
     hosts:
       - sonarr.bangedyour.mom

volumes:
  - hostPath:
      path: /media/tv
      type: ''
    name: tv
  - hostPath:
      path: /media/downloads
      type: ''
    name: downloads
  - hostPath:
      path: /media/config
      type: ''
    name: config
volumeMounts:
  - mountPath: /config
    name: config
    subPath: radarr/config
  - mountPath: /downloads
    name: downloads
    subPath: tv
  - mountPath: /tv
    name: tv

resources:
  requests:
    memory: 128Mi
    cpu: 0.1
  limits:
    memory: 256Mi
    cpu: 0.5

nodeSelector: {}

tolerations: []

affinity: {}