
replicaCount: 1

image:
  repository: linuxserver/code-server
  tag: latest
  pullPolicy: Always

env:
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"

service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - code-server.bangedyour.mom
  tls:
   - secretName: code-server-bangedyour-mom
     hosts:
       - code-server.bangedyour.mom
volumes:
  - name: config
    hostPath:
      path: /media/config
      type: DirectoryOrCreate
volumeMounts:
  - mountPath: /config
    name: config

nodeSelector: {}

tolerations: []

affinity: {}