
replicaCount: 1

image:
  repository: linuxserver/ombi
  tag: latest
  pullPolicy: IfNotPresent

env:
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"
  - name: "TZ"
    value: "US/New_York"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - ombi.bangedyour.mom
  tls:
   - secretName: ombi-bangedyour-mom
     hosts:
       - ombi.bangedyour.mom

volumes:
  - hostPath:
      path: /media/config
      type: ''
    name: config
volumeMounts:
  - mountPath: /config
    name: config
    subPath: ombi/config

nodeSelector: {}

tolerations: []

affinity: {}
