
replicaCount: 1

image:
  repository: linuxserver/prowlarr
  tag: latest
  pullPolicy: IfNotPresent

env:
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - prowlarr.bangedyour.mom
  tls:
   - secretName: prowlarr-bangedyour-mom
     hosts:
       - prowlarr.bangedyour.mom
volumes:
  - hostPath:
      path: /media/movies
      type: ''
    name: movies
  - hostPath:
      path: /media/downloads
      type: ''
    name: downloads
  - hostPath:
      path: /media/config
      type: ''
    name: config
volumeMounts:
  - mountPath: /config
    name: config
    subPath: prowlarr/config
  - mountPath: /downloads
    name: downloads
    subPath: movies
  - mountPath: /movies
    name: movies

nodeSelector: {}

tolerations: []

affinity: {}
