
replicaCount: 1

image:
  repository: fyb3roptik/threadfin
  tag: latest
  pullPolicy: Always

env:
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"

service:
  type: ClusterIP
  port: 34400

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - threadfin.bangedyour.mom
  tls:
   - secretName: threadfin-bangedyour-mom
     hosts:
       - threadfin.bangedyour.mom
volumeMounts:
  - mountPath: /data/conf
    name: config
    subPath: threadfin/config
  - mountPath: /data/temp
    name: temp

volumes:
  - hostPath:
      path: /media/config
      type: DirectoryOrCreate
    name: config
  - hostPath:
      path: /tmp/threadfin
      type: DirectoryOrCreate
    name: temp

nodeSelector: {}

tolerations: []

affinity: {}