
replicaCount: 1

image:
  repository: linuxserver/bazarr
  tag: latest
  pullPolicy: Always

env:
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - bazarr.bangedyour.mom
  tls:
   - secretName: bazarr-bangedyour-mom
     hosts:
       - bazarr.bangedyour.mom
volumes:
  - name: config
    hostPath:
      path: /media/config
      type: DirectoryOrCreate
  - name: movies
    hostPath:
      path: /media/movies
      type: DirectoryOrCreate
  - name: tv
    hostPath:
      path: /media/tv
      type: DirectoryOrCreate
volumeMounts:
  - mountPath: /config
    name: config
    subPath: bazarr/config
  - mountPath: /movies
    name: movies
  - mountPath: /tv
    name: tv

nodeSelector: {}

tolerations: []

affinity: {}