apiVersion: v1
kind: Service
metadata:
  name: {{ template "deluge.fullname" . }}
  labels:
    app: {{ template "deluge.name" . }}
    chart: {{ template "deluge.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8112
      protocol: TCP
      name: http
    - port: 6881
      targetPort: 6881
      protocol: TCP
      name: btor
    - port: 6881
      targetPort: 6881
      protocol: UDP
      name: btudp
  selector:
    app: {{ template "deluge.name" . }}
    release: {{ .Release.Name }}
